BASE <ex:> CONSTRUCT {
?s0 ?p0 _:g_2 .
_:g_2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:a0> .
_:g_2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_3 .
_:g_3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:g_0 .
_:g_3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:b0> .
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_1 .
_:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:c0> .
_:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_6 ?p0 ?o0 .
_:g_6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:a0> .
_:g_6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_7 .
_:g_7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:g_4 .
_:g_7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:b0> .
_:g_4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_5 .
_:g_5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:c0> .
_:g_5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>
} WHERE {
 ?s1 ?p1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
?s1 ?p1 <ex:a1> .
<http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> ?p2 ?o2 .
?s3 ?p3 _:g_8 .
_:g_8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:a3> .
_:g_8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
?s4 ?p4 _:g_9 .
_:g_9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:a4> .
_:g_9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_10 .
_:g_10 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:b4> .
_:g_10 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_11 .
_:g_11 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:c4> .
_:g_11 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
?s5 ?p5 _:g_14 .
_:g_14 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:a5> .
_:g_14 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_15 .
_:g_15 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:g_12 .
_:g_15 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_12 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:b5> .
_:g_12 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_13 .
_:g_13 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:c5> .
_:g_13 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_18 ?p6 ?o6 .
_:g_18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:a6> .
_:g_18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_19 .
_:g_19 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:g_16 .
_:g_19 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_16 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:b6> .
_:g_16 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_17 .
_:g_17 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:c6> .
_:g_17 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_20 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:a7> .
_:g_20 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:g_21 .
_:g_21 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> <ex:b7> .
_:g_21 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
?s8 ?p8 _:g_23 .
_:g_23 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> _:g_22 .
_:g_23 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
_:g_22 <ex:a8> <ex:b8> .
_:g_22 <ex:c8> <ex:d8> .
_:g_22 <ex:c8> <ex:e8> 
}