PREFIX : <https://ex.com/> SELECT ?a WHERE {
 <https://ex.com/a> ?a <https://ex.com/a> .
<https://ex.com/a> <https://ex.com/a> _:g_0 .
_:g_0 ( <https://ex.com/a>/<https://ex.com/a> ) <https://ex.com/a> 
}