PREFIX dbpedia-owl: <http://dbpedia.org/owl/#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT ?movie WHERE {
 ?movie <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/owl/#Film> .
?movie <http://dbpedia.org/owl/#starring> _:g_0 .
_:g_0 <http://www.w3.org/2000/01/rdf-schema#label> "Brad Pitt"@en .
_:g_0 ^<http://dbpedia.org/owl/#starring> ?otherMovie 
}