PREFIX dc: <http://purl.org/dc/elements/1.1/> INSERT { <http://example/egbook> <http://purl.org/dc/elements/1.1/title> "This is an example title"^^<http://www.w3.org/2001/XMLSchema#string> } WHERE {
 
}