PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> INSERT DATA { <http://example/book1> <http://purl.org/dc/elements/1.1/title> "A new book"^^<http://www.w3.org/2001/XMLSchema#string> } ;
INSERT DATA { <http://example/book2> <http://www.w3.org/2000/01/rdf-schema#label> "A second book"^^<http://www.w3.org/2001/XMLSchema#string> }