PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> SELECT ?person WHERE {
 ?person <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> FILTER ( EXISTS {
 ?person <http://xmlns.com/foaf/0.1/name> ?name 
} ) 
}