PREFIX : <http://example.com/ns#> SELECT * WHERE {
 ?s ?p ?o .
<http://example.com/ns#iri1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>> .
<http://example.com/ns#iri2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>> .
<http://example.com/ns#iri2> <http://example.com/ns#r1> ?Z1 .
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>> .
_:g_0 <http://example.com/ns#r2> ?Z2 .
<http://example.com/ns#iri3> <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>> .
<http://example.com/ns#iri3> <http://example.com/ns#r3> ?Z3 
}