PREFIX : <http://example.com/ns#> CONSTRUCT {
<http://example.com/ns#iri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>>
} WHERE {
 <http://example.com/ns#iri> <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>> 
}