PREFIX : <http://example.com/ns#> SELECT * WHERE {
 ?s <http://example.com/ns#p> ?o .
<http://example.com/ns#iri1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s <http://example.com/ns#p> ?o  )>> .
<http://example.com/ns#iri1> <http://example.com/ns#r1> ?Z1 .
<http://example.com/ns#iri2> <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s <http://example.com/ns#p> ?o  )>> .
<http://example.com/ns#iri2> <http://example.com/ns#r2> ?Z2 
}