PREFIX : <http://example.com/ns#> INSERT { <http://example.com/ns#s> ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>> .
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#s> ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>>  )>> .
_:g_0 ?Y <<( <http://example.com/ns#s1> <http://example.com/ns#p1> ?Z  )>> } WHERE {
 ?s ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>> .
_:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>>  )>> .
_:g_1 ?Y <<( <http://example.com/ns#s1> <http://example.com/ns#p1> ?Z  )>> 
}