PREFIX : <http://example.com/ns#> INSERT { ?S ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>> .
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?S ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>>  )>> .
_:g_0 ?Y ?Z } WHERE {
 <http://example.com/ns#s> ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>> .
_:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#s> ?P <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>>  )>> .
_:g_1 ?Y ?Z 
}