PREFIX : <http://example.com/ns#> CONSTRUCT {
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>>
} WHERE {
 _:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s ?p ?o  )>> 
}