PREFIX : <http://example.com/ns#> CONSTRUCT {
_:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#s> <http://example.com/ns#p> _:g_0  )>> .
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s <http://example.com/ns#p2> <http://example.com/ns#o2>  )>>
} WHERE {
 _:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#s> <http://example.com/ns#p> _:g_0  )>> .
_:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( ?s <http://example.com/ns#p2> <http://example.com/ns#o2>  )>> 
}