PREFIX : <http://example.com/ns#> SELECT * WHERE {
 _:g_0 <http://example.com/ns#b> <http://example.com/ns#c> .
_:g_0 ?Q _:g_1 .
_:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#s> ?P <http://example.com/ns#o>  )>> 
}