PREFIX : <http://example.com/ns#> INSERT { _:g_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>> .
_:g_0 ?P <http://example.com/ns#o2> .
_:g_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( _:g_0 ?P <http://example.com/ns#o2>  )>> .
_:g_1 ?Y _:g_2 .
_:g_2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#s1> <http://example.com/ns#p1> ?Z  )>> } WHERE {
 _:g_3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#a> <http://example.com/ns#b> <http://example.com/ns#c>  )>> .
_:g_3 ?P <http://example.com/ns#o1> .
_:g_4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( _:g_3 ?P <http://example.com/ns#o1>  )>> .
_:g_4 ?Y _:g_5 .
_:g_5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#reifies> <<( <http://example.com/ns#s1> <http://example.com/ns#p1> ?Z  )>> 
}