PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> SELECT DISTINCT ?product ?productLabel WHERE {
 ?product <http://www.w3.org/2000/01/rdf-schema#label> ?productLabel FILTER ( ( <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product28> != ?product ) ) <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product28> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productFeature> ?prodFeature .
?product <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productFeature> ?prodFeature .
<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product28> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1> ?origProperty1 .
?product <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric1> ?simProperty1 FILTER ( ( ( ?simProperty1 < ( ?origProperty1 + "120"^^<http://www.w3.org/2001/XMLSchema#integer> ) ) && ( ?simProperty1 > ( ?origProperty1 - "120"^^<http://www.w3.org/2001/XMLSchema#integer> ) ) ) ) <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product28> <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric2> ?origProperty2 .
?product <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyNumeric2> ?simProperty2 FILTER ( ( ( ?simProperty2 < ( ?origProperty2 + "170"^^<http://www.w3.org/2001/XMLSchema#integer> ) ) && ( ?simProperty2 > ( ?origProperty2 - "170"^^<http://www.w3.org/2001/XMLSchema#integer> ) ) ) ) 
} ORDER BY ( ?productLabel ) LIMIT 5