PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/> SELECT ?name WHERE {
 ?x <http://xmlns.com/foaf/0.1/givenName> ?name OPTIONAL {
 ?x <http://purl.org/dc/elements/1.1/date> ?date 
} FILTER ( !bound( ?date ) ) 
}