PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX ns: <http://example.org/ns#> SELECT ?title ( ( ?p * ( "1"^^<http://www.w3.org/2001/XMLSchema#integer> - ?discount ) ) AS ?price ) WHERE {
 ?x <http://example.org/ns#price> ?p .
?x <http://purl.org/dc/elements/1.1/title> ?title .
?x <http://example.org/ns#discount> ?discount 
}