PREFIX dc10: <http://purl.org/dc/elements/1.0/>
PREFIX dc11: <http://purl.org/dc/elements/1.1/> SELECT ?x ?y WHERE {
 {
 ?book <http://purl.org/dc/elements/1.0/title> ?x 
} UNION {
 ?book <http://purl.org/dc/elements/1.1/title> ?y 
} 
}