PREFIX foaf: <http://xmlns.com/foaf/0.1/> SELECT ?person ?interest ?known WHERE {
 SERVICE <http://people.example.org/sparql> {
 ?person <http://xmlns.com/foaf/0.1/name> ?name OPTIONAL {
 ?person <http://xmlns.com/foaf/0.1/interest> ?interest SERVICE <http://people2.example.org/sparql> {
 ?person <http://xmlns.com/foaf/0.1/knows> ?known 
} 
} 
} 
}